/****************************************************************************************************/
/*                    https ://github.com/Mrliu88888888/QJsonOnline                                 */
/****************************************************************************************************/
#include <QtCore/QCoreApplication>
#include <qjsondocument.h>
#include <qjsonarray.h>
#include <qjsonobject.h>
#include <qfile.h>
#include <qtextcodec.h>
#include <qdebug.h>

#define ENABLE_CLASS

inline QString firstCharToUpper(const QString& str, const QString& beginStr = "")
{
    return beginStr + str.at(0).toUpper() + str.mid(1);
}

#ifdef ENABLE_CLASS
QString pJsonObject(const QJsonObject& obj, const QString& objName = "MyClass", bool isClass = true);
#else
QString pJsonObject(const QJsonObject& obj, const QString& objName = "MyStruct", bool isClass = false);
#endif

QString pJsonArray(const QJsonArray& arr, QList<QPair<QString, QString>>& ls, const QString& key, bool isClass);

/// @brief
/// @param filename
/// @return 0: 成功
///         1: 打开读文件失败
///         2: Json为空
///         3: Json类型未知
///         4: 打开写文件失败
///         5: 不支持Json Array的解析
int json2cpp(const QString& filename)
{
    QFile fin(filename + ".json");
    if (!fin.open(QIODevice::ReadOnly)) {
        return 1;
    }
    auto doc = QJsonDocument::fromJson(fin.readAll());
    fin.close();

    if (doc.isNull()) {
        return 2;
    }
    QString res;
    if (doc.isObject()) {
        res = pJsonObject(doc.object());
    }
    else if (doc.isArray()) {
        // res = pJsonArray(doc.array());
        return 5;
    }
    else {
        return 3;
    }

    QFile fout(filename + ".cpp");
    if (!fout.open(QIODevice::WriteOnly)) {
        return 4;
    }
    res.insert(0, "# Generated by QJsonOnline\n# https://github.com/Mrliu88888888/QJsonOnline\n\n");
    fout.write(res.toUtf8());
    fout.flush();
    fout.close();
    return 0;
}

int main(int argc, char* argv[])
{
    QCoreApplication a(argc, argv);
    QTextCodec::setCodecForLocale(QTextCodec::codecForName("UTF-8"));

    const QString filename = "ip";
    qDebug() << json2cpp(filename);

    return 0;
}

#ifdef ENABLE_CLASS
QString pJsonObject(const QJsonObject& obj, const QString& objName, bool isClass)
#else
QString pJsonObject(const QJsonObject& obj, const QString& objName, bool isClass)
#endif
{
    QString res;
    QList<QPair<QString, QString>> ls;
    for (const auto& key : obj.keys()) {
        const auto& v = obj.value(key);
        if (v.isObject()) {
            const auto& className = isClass ? firstCharToUpper(key) : firstCharToUpper(key, "S");
            res += pJsonObject(v.toObject(), className);
            ls.append(QPair<QString, QString>(className, key));
        }
        else if (v.isArray()) {
            const auto& arr = v.toArray();
            res += pJsonArray(arr, ls, key, isClass);
        }
        else if (v.isBool()) {
            ls.append(QPair<QString, QString>("bool", key));
        }
        else if (v.isDouble()) {
            ls.append(QPair<QString, QString>("double", key));
        }
        else if (v.isString()) {
            ls.append(QPair<QString, QString>("QString", key));
        }
        else {
            qDebug() << "else type: " << v;
        }
    }

    {
        res.append(isClass ? "class " : "struct ");
        res.append(objName);
        res.append("\n{\n");
        res.append(QString("\t%1() {}\n\n").arg(objName));
        for (const auto& r : ls) {
            res.append(QString("\t%1 %2;\n").arg(r.first).arg(r.second));
        }
        res.append("\n\tQJSON_ONLINE(" + objName + ",");
        for (const auto& r : ls) {
            res.append(QString("%1,").arg(r.second));
        }
        res.chop(1);
        res.append(");\n");
        res.append("};\n\n");
    }
    return res;
}

QString pJsonArray(const QJsonArray& arr, QList<QPair<QString, QString>>& ls, const QString& key, bool isClass)
{
    QString res;
    if (arr.size() > 0) {
        const auto& c = arr.at(0);
        QString type;
        if (c.isObject()) {
            const auto& className = isClass ? firstCharToUpper(key) : firstCharToUpper(key, "S");
            res += pJsonObject(c.toObject(), className);
            type = className;
        }
        else if (c.isArray()) {
            type = QString("QList<%1>").arg("");
        }
        else if (c.isBool()) {
            type = "bool";
        }
        else if (c.isDouble()) {
            type = "double";
        }
        else if (c.isString()) {
            type = "QString";
        }
        else {
            qDebug() << "else type: " << c;
        }
        ls.append(QPair<QString, QString>(QString("QList<%1>").arg(type), key));
    }
    return res;
}
